CREATE DATABASE temp1;
DROP DATABASE temp1;
create database temp2;
DROP DATABASE temp2;
CREATE DATABASE chetana;
DROP DATABASE chetana;
DROP DATABASE pilli;
CREATE DATABASE IF NOT EXISTS chetana;
DROP DATABASE cing;
DROP DATABASE IF EXISTS cing;


CREATE DATABASE college;
CREATE DATABASE chetana;
USE college;

CREATE TABLE student(
id INT PRIMARY KEY,
name VARCHAR(50),
age INT NOT NULL
);

INSERT INTO student VALUES(1,"CHETANA",85);
INSERT INTO student VALUES(2,"CHEEKU",18);
SELECT *FROM student;

SHOW DATABASES;
SHOW TABLES;
DROP DATABASE student;
DROP TABLE student;
DROP DATABASE college;
