CREATE DATABASE payment;
USE payment;
CREATE TABLE details(
id INT PRIMARY KEY,
name VARCHAR(50),
mode VARCHAR(50),
city VARCHAR(50)
 );
INSERT INTO details
(id,name,mode,city)
 VALUES
 (101,"OLIVIA","NETBANKING","PORTLAND"),
 (102,"ETHAN","CREDIT CARD","MIAMI"),
(103,"MAYA","CREDIT CARD","SEATLE"),
(104,"LIAM","NETBANKING","DENVER"),
(105,"SOPHIA","CREDIT CARD","NEW ORLEANS"),
(106,"CALEB","DEBIT CARD","MINNEAPOLIS"),
(107,"AVA","DEBIT CARD","PHONEIX"),
(108,"LUCAS","NETBANKING","BOSTON"),
(109,"ISABELLA","NETBANKING","NASHVILLE"),
(110,"JACKSON","CREDIT CARD","BOSTON");
SELECT mode , COUNT(name)FROM details GROUP BY mode; 
 